Give warning, no error, will be retried.
Amsterdam/GOB-BagExtract pull request #15
Opened 2021-03-29 09:57 UTC by fzonneveld-adam

Giving errors in log, will retry job, resulting in 2 errors.
Warning is sufficient here. When jobs are done every day, mutations files should be ready for the previous day.

2021-03-30 12:51 UTC, jasper-jager requested changes

2021-03-31 08:50 UTC, fzonneveld-adam commented on src/gobbagextract/__main__.py
> +        if interval.days > 5:
Made the configurable inf the config.py and env variable.

2021-03-31 08:53 UTC, fzonneveld-adam commented on src/tests/test_main.py
> +        _log_no_more_left(logger, last_import)
Yes I must check here. Done.

2021-04-06 07:24 UTC, jasper-jager approved these changes

2021-04-06 07:24 UTC, merged